// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpFC32FuZaDBSX3giUTTLZSt3vtaSEtQQ',
    appId: '1:71598494098:web:a17475970da5888918314b',
    messagingSenderId: '71598494098',
    projectId: 'hosta-13e66',
    authDomain: 'hosta-13e66.firebaseapp.com',
    storageBucket: 'hosta-13e66.firebasestorage.app',
    measurementId: 'G-Z9G062H35C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0eSmVFxVWNJa-EfVXIXlxbjVi2rHZq4',
    appId: '1:71598494098:android:dbf6ae812514682518314b',
    messagingSenderId: '71598494098',
    projectId: 'hosta-13e66',
    storageBucket: 'hosta-13e66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV3xNQf2GlZKGmbHvga5sUOJwe9_4l7XY',
    appId: '1:71598494098:ios:bb1cfb5d1274d03c18314b',
    messagingSenderId: '71598494098',
    projectId: 'hosta-13e66',
    storageBucket: 'hosta-13e66.firebasestorage.app',
    iosBundleId: 'com.example.hostaProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV3xNQf2GlZKGmbHvga5sUOJwe9_4l7XY',
    appId: '1:71598494098:ios:bb1cfb5d1274d03c18314b',
    messagingSenderId: '71598494098',
    projectId: 'hosta-13e66',
    storageBucket: 'hosta-13e66.firebasestorage.app',
    iosBundleId: 'com.example.hostaProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpFC32FuZaDBSX3giUTTLZSt3vtaSEtQQ',
    appId: '1:71598494098:web:b7725dc5ba05d12718314b',
    messagingSenderId: '71598494098',
    projectId: 'hosta-13e66',
    authDomain: 'hosta-13e66.firebaseapp.com',
    storageBucket: 'hosta-13e66.firebasestorage.app',
    measurementId: 'G-ENZXQC3MFD',
  );
}
