// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsVLPN80sDT82hTsjJct6M0wA7dzAOIY',
    appId: '1:228330636918:web:6a5286d4eb430cf50e0157',
    messagingSenderId: '228330636918',
    projectId: 'servicesapp-af7d1',
    authDomain: 'servicesapp-af7d1.firebaseapp.com',
    storageBucket: 'servicesapp-af7d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdgc7MTYklix1LF5PBUtPkmuGfS_vEdQI',
    appId: '1:228330636918:android:dcb9bd6549adf2ea0e0157',
    messagingSenderId: '228330636918',
    projectId: 'servicesapp-af7d1',
    storageBucket: 'servicesapp-af7d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlG6jXPIaujP48KoQPLRDYXiRhwZKap0c',
    appId: '1:228330636918:ios:50a38e07926e7af60e0157',
    messagingSenderId: '228330636918',
    projectId: 'servicesapp-af7d1',
    storageBucket: 'servicesapp-af7d1.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlG6jXPIaujP48KoQPLRDYXiRhwZKap0c',
    appId: '1:228330636918:ios:50a38e07926e7af60e0157',
    messagingSenderId: '228330636918',
    projectId: 'servicesapp-af7d1',
    storageBucket: 'servicesapp-af7d1.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZsVLPN80sDT82hTsjJct6M0wA7dzAOIY',
    appId: '1:228330636918:web:1f65bcb4fe806b490e0157',
    messagingSenderId: '228330636918',
    projectId: 'servicesapp-af7d1',
    authDomain: 'servicesapp-af7d1.firebaseapp.com',
    storageBucket: 'servicesapp-af7d1.appspot.com',
  );

}