// ignore_for_file: non_constant_identifier_names

class SharedPreferencesKeys {
  static String PREFS_KEY_USER_LOGGED_IN = 'PREFS_KEY_USER_LOGGED_IN';
  static String PREFS_KEY_LANGUAGE = 'PREFS_KEY_LANGUAGE';
  static String PREFS_KEY_THEME = 'PREFS_KEY_THEME';
  static String PREFS_KEY_USER = 'PREFS_KEY_USER';
  static String PREFS_KEY_FIRST_USE = 'PREFS_KEY_FIRST_USE';
  static String PREFS_KEY_SYNC_TYPE = 'PREFS_KEY_SYNC_TYPE';
  static String PREFS_KEY_SYNC_DATE = 'PREFS_KEY_SYNC_DATE';
  static String PREFS_KEY_SYNC_CAN_SYNC = 'PREFS_KEY_SYNC_CAN_SYNC';
  static String PREFS_KEY_COLLECTIONS_NAMES = 'PREFS_KEY_COLLECTIONS_NAMES';
  static String PREFS_KEY_LOCALLY_TABLES = 'PREFS_KEY_LOCALLY_TABLES';
  static String PREFS_KEY_LOCALLY_CHARTS = 'PREFS_KEY_LOCALLY_CHARTS';
  static String PREFS_KEY_LOCALLY_ITEMS = 'PREFS_KEY_LOCALLY_ITEMS';
 
  static String PREFS_KEY_LOCALLY_CATEGORIES =
      'PREFS_KEY_LOCALLY_CATEGORIES';
 
  static String PREFS_KEY_LOCALLY_DELIVERY_NAMES =
      'PREFS_KEY_LOCALLY_DELIVERY_NAMES';
  static String PREFS_KEY_LOCALLY_DELIVERY_LOCATIONS =
      'PREFS_KEY_LOCALLY_DELIVERY_LOCATIONS';
  static String PREFS_KEY_LOCALLY_DELIVERY_CLIENTS =
      'PREFS_KEY_LOCALLY_DELIVERY_CLIENTS';
  
}
